options:
  tools:
    type: string
    default: git gcc make bzr
    description: Tooling to deploy alongside jenkins
  release:
    type: string
    default: lts
    description: >
      Source of Jenkins, options include:
      - lts: use the most recent Jenkins LTS release.
      - trunk: use the most recent Jenkins release.
      - bundle: use a bundled deb package. The bundle-site configuration should 
      be set or the jenkins deb package needs to be manually copied over to the 
      charm files/ dir before deployment and named jenkins.deb. It can be 
      downloaded from http://pkg.jenkins-ci.org/debian/
      - http(s)://...: http(s) link to a retrievable jenkins deb
  bundle-site:
    type: string
    default: ""
    description: >
      Site to download deb packages from when installing jenkins from bundle. 
      If this configuration is not set, the jenkins deb package needs to be manually 
      copied over to the charm files/ dir before deployment and named jenkins.deb.
  username:
    type: string
    default: admin
    description: Admin user username - used to manage
      slave nodes so please don't change in Jenkins.
  password:
    type: string
    default: ""
    description: >
      Admin user password, will be auto-generated if not set. Can be retrieved
      via the get-admin-credentials action. This is used to manage slave nodes so
      please don't change in Jenkins.
  plugins:
    type: string
    default: ""
    description: Space separated list of plugins to install
  plugins-site:
    type: string
    default: "https://updates.jenkins-ci.org/latest/"
    description: Site to download plugin .hpi files from.
  plugins-check-certificate:
    type: string
    default: "yes"
    description: Set to no to allow downloading from an invalid https site.
  plugins-auto-update:
      type: boolean
      default: False
      description: >
        This option enables auto update for plugins. The routine will check for
        new versions available based on Update Center's info, will update them
        through jenkins and safe-restart once completed.
  plugins-auto-update-interval:
      type: int
      default: 1440
      description: >
        Interval which the auto-update will try to run (in minutes).
  proxy-hostname:
    type: string
    default: ""
    description: |
      If a proxy is required for Jenkins to download plugins and updates, set its
      hostname or IP address here, e.g. "proxy.example.tld" or "10.0.0.1".
  proxy-port:
    type: int
    default: 3128
    description: |
      If a proxy is required for Jenkins to download plugins and updates, set its
      port number here. Ignored if proxy-hostname is not also set.
  proxy-username:
    type: string
    default: ""
    description: |
      If a proxy is required for Jenkins to download plugins and updates and
      authentication is also required, set the username here. Ignored if
      proxy-hostname is not also set.
  proxy-password:
    type: string
    default: ""
    description: |
      If a proxy is required for Jenkins to download plugins and updates and
      authentication is also required, set the password here. Ignored if
      proxy-hostname and proxy-password are not both also set.
  remove-unlisted-plugins:
    type: string
    default: "no"
    description: |
      Set this to yes to remove any plugins not listed in plugins
      from the installation.
  master-executors:
    type: int
    default: 1
    description: |
      Number of executors to configure for jenkins master.
  public-url:
    type: string
    default: ""
    description: |
      Public url of Jenkins frontend, including the hostname and prefix. This
      is used by Jenkins whenever generating full links.
  jnlp-port:
    type: int
    default: 48484
    description: |
      TCP port on which to listen for incoming connections from slaves.
      Set to -1 for a random port, or to 0 to disable JNLP entirely.
  update-center:
    type: string
    default: ""
    description: |
      Configure a custom Update Center instead of getting plugins from updates.jenkins-ci.org.
      Provide the whole path to update-center.json file.
      Example: https://your-domain.com/current/update-center.json
  update-center-ca:
    type: string
    default: ""
    description: |
      CA certificate for the update-center. This is required when setting update-center
      because jenkins won't be able to validate your custom Update Center without it.
